#!/bin/bash

# compile list library
../utils/compile list.anita list.c -as-lib -o list.bc -cflags --eh=none -V

# compile unittest
gcc -x c -w -E -I. -D__FILE__=\"list_ut.anita\" list_ut.anita | ../utils/compile - -libs list -V -cflags --eh=none

